"""
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXIjn2yS7ZcWezanhmp1fho4hcs0p6tW
"""

from rag_src.doc_context_enricher.base import BaseContextEnricher
from typing import List

class DocSummarizer(BaseContextEnricher):
    """
    This module summarizes each document using the LLM
    It helps reduce the size and the noise in the retrieved context.
    """

    def __init__(self, llm):
        self.llm = llm

    def enrich(self, docs: List[str]) -> List[str]:
        summaries = []
        for doc in docs:
            prompt = f"Summarize the following document in 1-2 lines:\n\n{doc}"
            try:
                summary = self.llm.generate(prompt)
            except:
                summary = doc  # fallback: keep original doc
            summaries.append(summary)
        return summaries